### ISSUE TITLE
Verog the Dervish does not spawn (or requires an excessive amount of kills)

### ISSUE THREAD

**Issue by Kaporalhart** [slowtorta/turtlewow-bug-tracker#1381]
This issue existed and was previously closed, but i encountered it again today.

Please, provide a clear description what the bug is:
Verog the Dervish does not spawn for the quest to kill him and take his head.

Steps to reproduce the behavior with as much detail as possible:

Come at the stagnant oasis, in the barrens. Slay dozens of centaurs, realize he fails to appear.

IDs of affected creatures, items, quests or spells with a link to the relevant page:

NPC: https://database.turtle-wow.org/?npc=3395
Item: https://database.turtle-wow.org/?item=5023
Quest: https://database.turtle-wow.org/?quest=851
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

Expected behavior. Describe how it should work:
Verog should appear after you kill a few centaurs near his command tent or in the nearby oasis.

**Comment by slowtorta** [comment]
Fixed in the next revision.

**Comment by CantCastThatYet** [comment]
Still not working. Literally done 3 circles around stagnant oasis eliminating everything that even remotely looks like centaur. Nothing spawned yet.
Doing it as a lvl 34 feral druid so killing is pretty fast.
