### ISSUE TITLE
The Thunderhorn Cleansing Totem is only usable by Taurens

### ISSUE THREAD

**Issue by FeyfolkenFantasy** [slowtorta/turtlewow-bug-tracker#1733]
**Please, provide a clear description what the bug is:**

The Thunderhorn Cleansing Totem is only usable by Taurens.
I read on Discord that it was supposed to be fixed by a short maintenance scheduled on the 07/29/22.

![WoWScrnShot_073022_062239](https://user-images.githubusercontent.com/102554573/181872565-6893ae1a-c461-4eff-9948-8bfec3d9026b.jpg)

**Steps to reproduce the behavior with as much detail as possible:**

1. Go to th Bloodhoof Village (Mulgore) and start the quest chain from Mull Thunderhorn.
2. The fourth quest asks you to use the Thunderhorn cleansing totem which you can not use if you are not a Tauren.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=2948
Item: https://database.turtle-wow.org/?item=5415
Quest: https://database.turtle-wow.org/?quest=758

**Expected behavior. Describe how it should work:**

As any Horde race can now do this quest chain, this item shall by usable by any Horde race.

**Comment by slowtorta** [comment]
I cannot reproduce your issue, the quest is there and it's available for my orc character: 
![image](https://user-images.githubusercontent.com/66763404/181903080-16ca294d-c135-4f6c-b46d-e906889619d6.png)

**Comment by FeyfolkenFantasy** [comment]
Dear Torta, I did receive your email with your screenshot showing your orc with the completed quest log. And the issue was somehow solved as I could finish this quest.
But now I am having the exact same issue with the next quest totem (see the screenshot below).
![WoWScrnShot_073022_214223](https://user-images.githubusercontent.com/102554573/181992444-ccaeb101-a695-4d6c-b210-79d173ebf787.jpg)

I did make sure to delete my WDB folder before taking those two totem screenshots and I did try to use the items aswell without succes.
I must admit that I don't understand what is going on. Maybe an issue related to goblins?

**Comment by slowtorta** [comment]
> Dear Torta, I did receive your email with your screenshot showing your orc with the completed quest log. And the issue was somehow solved as I could finish this quest. But now I am having the exact same issue with the next quest totem (see the screenshot below). ![WoWScrnShot_073022_214223](https://user-images.githubusercontent.com/102554573/181992444-ccaeb101-a695-4d6c-b210-79d173ebf787.jpg)
> 
> I did make sure to delete my WDB folder before taking those two totem screenshots and I did try to use the items aswell without succes. I must admit that I don't understand what is going on. Maybe an issue related to goblins?

It was fixed and it's fixed on my end, I tried it with the Goblin as well. Could you try to delete your WDB once again and see if you can use this item?
![image](https://user-images.githubusercontent.com/66763404/181994635-444ead1a-f723-41b9-bfbf-64f72b460251.png)

**Comment by FeyfolkenFantasy** [comment]
I am not sure if you got my answer as I answered to you directly by mail.
I deleted my WDB folder once again and I still get the red tag "Races: Tauren" on the totem and still can't use it.
I feel stupid to waste your time with such a issue.
I am not in a hurry and I don't mind if I can't finish the quest right now.

**Comment by slowtorta** [comment]
Damn, that's so crazy. It has no restriction for me, also look, this is the
value directly in the database from the production server:
[image: image.png]

**Comment by slowtorta** [comment]
I'm sorry, this heat gets me really hard. It's the next quest in the chain... Fixing this one as well >.<

**Comment by FeyfolkenFantasy** [comment]
No worries, we are also melting here in France. Thank you very much for your very quick replies though! Much respect for being everywere at anytime!

**Comment by FeyfolkenFantasy** [comment]
Waou! Thank you very much for your reactivity! Well I have deleted my WDB
folder once again and the red quote "Races: Tauren" is still there. And
when I click on it, it says: you can't use that item.
Not a big deal if I can not finish the quest today though. I am not in a
hurry.
I feel quite bad to waste your time.
