### ISSUE TITLE
Trueshot Cast Delay and Melee Weave

### ISSUE THREAD

**Issue by SabineWren** [slowtorta/turtlewow-bug-tracker#1742]
Aimed Shot and Multi-Shot fire when the cast finishes. Trueshot has a delay after the cast, during which movement will cancel the shot. This delay results in Auto Shots clipping at fast attack speeds (around 2.2 weapon speed or lower).

**Steps to reproduce the behavior with as much detail as possible:**

1. Cast Trueshot at a target dummy.
2. Move immediately after the cast completes.
3. Notice Trueshot doesn't fire.

**Expected behavior. Describe how it should work:**
No idea! Is the delay intended? If so, is it a constant value that castbar addons can show?

**Comment by Francesq** [comment]
Trueshot also turn mêlée swing on cd so we can’t weave after using trueshot (unsing raptor strike or normal melee swing when the mob go to melee, same in pvp)

**Comment by SabineWren** [comment]
Related:
#1647 Not starting Auto Shot
#1751 Breaking Feign Death

**Comment by Francesq** [comment]
Another issue with trueshot : it is not affected by hawk aspect procs (from talent) and rapid fire which means you finally clip your auto shot when attack speed increase.

**Comment by Francesq** [comment]
In addition, there is some delay in casting aimed shot too. The duration of the cas is more than 3 seconds, maybe 3.5 like it is more than 1 sec for trueshot (maybe 1.5).

**Comment by ratkosrb** [comment]
Should be fixed by https://github.com/slowtorta/turtle-wow/commit/d43c170dece7856500e432ff85a5d08536340d68

**Comment by SabineWren** [comment]
I don't think this issue should have been closed, as the spellbook still shows a 1 second cast time. There's definitely a delay, but the delay isn't consistent across haste procs.

1.0 second bar
https://user-images.githubusercontent.com/18298014/203809110-55737914-e1f4-4f1d-978f-c1c179f6dbd0.mp4

1.35 second bar
https://user-images.githubusercontent.com/18298014/203809144-dd961a72-3233-4f87-9707-47d46ab515e8.mp4

1.35 second bar + haste procs
https://user-images.githubusercontent.com/18298014/203809199-08174822-d424-4105-83c2-917bf45817e6.mp4
