### ISSUE TITLE
Insect swarm can't be learned beyond rank 2

### ISSUE THREAD

**Issue by leylandpaladin** [slowtorta/turtlewow-bug-tracker#1804]
Insect swarm can't be learned beyond rank 2. When i speak with trainer it looks like rank 3 is missing from the list.

1. Find you closest druid trainer and try to learn insect swarm beyond level 2

![insect swarm turtles](https://user-images.githubusercontent.com/45656368/182569666-8547d79a-e2fb-4810-a1a6-ea4d49a39a8b.png)

Expected behavior. Describe how it should work:

Insect swarm maximum rank is 5
Idk if every druid have this problem maybe it's just me.

**Comment by Mozaiczny** [comment]
It's funny. Trainer at **Dolanaar** got rank 1 and rank 3, but not rank 2! :D 

![image](https://user-images.githubusercontent.com/46848544/182697546-55fa7820-f252-4e73-905a-684b216fdb04.png)

It should be fixed, but hey! You can go and buy **Insect Swarm** here!

**Comment by leylandpaladin** [comment]
![no insect swarm](https://user-images.githubusercontent.com/45656368/183145946-80967c14-38b8-45ea-915b-07f937b22727.png)

It's missing for me even there!

**Comment by Testerrosaurus** [comment]
Rank 2 version (should be available level 30) of the spell was still missing from trainer as of 2 days ago (12.08.2022).
Learned rank 3 version which was available at level 40 2 days ago when i got level 40 on my druid. But in fact it learned rank 2 spell (and the trainer tooltip was strange, saying it's rank3 requiring rank1). At level 40 druid should have rank 3.

**Comment by leylandpaladin** [comment]
The issue was fixed manually by GM (thanks a lot). I hope it already was fixed manualy
