### ISSUE TITLE
[Paladin] Judgement of Righteousness sometimes evades or does nothing

### ISSUE THREAD

**Issue by Velite12** [slowtorta/turtlewow-bug-tracker#1953]
Sometimes, Judgement of Righteousness will not do anything when used. It doesn't even say the spell is resisted.

https://database.turtle-wow.org/?spell=20187 and all other ranks

![image](https://user-images.githubusercontent.com/45871932/184909931-dc08ca27-5042-41ee-8856-222744f33787.png)
![image](https://user-images.githubusercontent.com/45871932/184909886-1aa34da6-9ab0-48d2-86f1-b24c3b1da7bc.png)
![image](https://user-images.githubusercontent.com/45871932/184909900-bb1ae7d0-1233-4bb0-92cd-2536a2981145.png)

How it should work:

If judgement of righteousness resists, it should say that it was resisted. If judgement of righteousness lands, it should show the damage resisted, if any, alongside the damage done. It should not do nothing.

**Comment by geojak** [comment]
yea i have also confirmed this bug just ow. wtf

**Comment by blade7606** [comment]
confirmed this bug is still around

**Comment by redmagejoe** [comment]
Cannot reproduce this on current version.

Fixed.

**Comment by twowTurtReynolds** [comment]
Reopening, this bug is still around to this day:

https://cdn.discordapp.com/attachments/810850211571171328/1181377125354323968/sor.mp4?ex=6580d62f&is=656e612f&hm=48b4349f53225223080c0aff7a3251e239ce535d88f17ca7443fe000d94f5247&

**Comment by Giperion** [comment]
![изображение](https://github.com/slowtorta/turtlewow-bug-tracker/assets/10399905/156e3081-78bc-412d-9a2b-9efcc182fbfb)

**Comment by Giperion** [comment]
There was a problem in the core, that doesn't report spells to be resisted in combat log. That was happening with JoR.

**Comment by Giperion** [comment]
According to spell and core information, Judgement of Righteousness is a spell that deal damage, but still can be resisted. Either by magic school or by chance. This chance is increased, if a level difference is presented. In case of 60 player fighting 63 elite mob, there is a 15% chance of "Judgement of Righteousness" to miss.
When it happening, core should also inform about that client, but it didn't do that. I fix that part, but the spell will still be resisted, as it should.
