### ISSUE TITLE
Violet Tragan Poison Mushroom

### ISSUE THREAD

**Issue by Iacov** [slowtorta/turtlewow-bug-tracker#2015]
**Please, provide a clear description what the bug is:**

**Steps to reproduce the behavior with as much detail as possible:**

1. [Violet Tragan] is dotting 10x / 1second
![image](https://user-images.githubusercontent.com/6597238/186975045-d5da4d49-765b-4b37-a4c0-e1b988cd919c.png)
It currently ticks faster than one can count, according to old wowhead comments the debuff deals correct dmg but it ticks too often.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=7583
Item: https://database.turtle-wow.org/?item=8526
Quest: https://database.turtle-wow.org/?quest=2641
Spell: https://database.turtle-wow.org/?spell=6727
Object: https://database.turtle-wow.org/?object=141853

**Expected behavior. Describe how it should work:**
The [Poison Mushroom] debuffs it produces should tick 10 damage / second.

**Comment by slowtorta** [comment]
It's probably fixed in this update: https://forum.turtle-wow.org/viewtopic.php?f=63&t=4601

_Fixed an ancient bug that caused permanent periodic damage auras on creatures, like the disease cloud on abominations, to start ticking faster and faster over time, eventually one-shotting players that go near the creature if the server is online long enough._

**Comment by Iacov** [comment]
> It's probably fixed in this update: https://forum.turtle-wow.org/viewtopic.php?f=63&t=4601
> 
> _Fixed an ancient bug that caused permanent periodic damage auras on creatures, like the disease cloud on abominations, to start ticking faster and faster over time, eventually one-shotting players that go near the creature if the server is online long enough._

Hi, please test item, not fixed: 
![image](https://user-images.githubusercontent.com/6597238/197311122-b90278c8-c788-4232-b213-d36f02166d3c.png)
10 procs / per second

**Comment by Iacov** [comment]
@slowtorta ^
