### ISSUE TITLE
The elemental invassions bosses loot drop is bugged

### ISSUE THREAD

**Issue by Tinyfin-github** [slowtorta/turtlewow-bug-tracker#255]
The elemental invassions bosses loot drop is bugged. Players are encountering one  or more of the following problems:

- The elemental bosses  don't drop any loot
- When killing  the elemental invasion bosses the party  does not get the loot even if they rolled for it
- The elemental bosses are despawning  really fast after being killed and players  losing the loot as a result.

https://database.turtle-wow.org/?npc=14461 Baron Charr
https://database.turtle-wow.org/?npc=14464 Avalanchion
https://database.turtle-wow.org/?npc=14457 Princess Tempestria
https://database.turtle-wow.org/?npc=14454 The Windreaver

**Comment by jameyboor** [comment]
Possible fix on PTR. Needs testing.

**Comment by gabor-varga** [comment]
After yesterday's patch we killed https://database.turtle-wow.org/?npc=14461 Baron Charr and the same issue happened. According to the patch notes this should have been fixed.

**Comment by terraform123** [comment]
Hi, after yesterday's patch has been applied, the same issue happened to me with https://database.turtle-wow.org/?npc=14461 Baron Charr. Despite the patch notes mentioning the issue being fixed, it still seems to be present.

**Comment by jameyboor** [comment]
Thank you, I will take a look.

**Comment by jameyboor** [comment]
Another possible fix has been rolled out and will be active on next Server update.

**Comment by Tinyfin-github** [comment]
Player reports that the issue still persists even after the second fix.

**Comment by jameyboor** [comment]
Fixed next update.

**Comment by OonaQueenoftheBae** [comment]
Hello, reporting that this is certainly still happened. The Corpses are despawning very quickly. Currently the workaround is FFA Loot and loot the mob really fast. Since these bosses drop a material for the new Elemental gear hopefully another fix for it can be tried!

**Comment by Velite12** [comment]
![image](https://user-images.githubusercontent.com/45871932/186030497-0280d273-634c-4e3f-bf49-9fbb1baee111.png)
Reporting here that this is not fixed for Avalanchion, he despawned 5 seconds after kill.

**Comment by Velite12** [comment]
![image](https://user-images.githubusercontent.com/45871932/186031054-14d0c10f-886e-4e7c-a5b5-70934babe79f.png)
Also happening for the regular mobs too.
