### ISSUE TITLE
Quest: Minor Magical Fortifications won't complete.

### ISSUE THREAD

**Issue by Aeliren** [slowtorta/turtlewow-bug-tracker#2788]
The quest "Minor Magical Fortifications" from Magus Palon at Dalaran does not allow me to complete it even though I have the required items. I've attempted to disassemble the essences back into their lesser forms and then reassembling them into their greater forms, as well as relogging and clearing my WDB to no effect.

![image](https://user-images.githubusercontent.com/96898927/215675457-4b1c17d7-77ae-4a58-8391-b5efe1f6ea4e.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Acquire the quest "Minor Magical Fortifications" from Magus Palon at Dalaran in the Alterac Mountains.
2. Have three Greater Mystic Essences in your bag.
3. Attempt to turn in the quest.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=61065
Item: https://database.turtle-wow.org/?item=11135
Quest: https://database.turtle-wow.org/?quest=40709

**Expected behavior. Describe how it should work:**

I should be capable of turning in my quest when I have the three Greater Mystic Essences.

**Comment by cyaohiri** [comment]
Abandoning and retaking the quest should fix it.

**Comment by gabryatfendor** [comment]
Still not working for me. Tried to delete WDB folder and abandon/retake the quest multiple times, still can't complete the quest

**Comment by SabineWren** [comment]
Same with Major Magical Fortifications

**Comment by geojak** [comment]
@slowtorta this issue is still present? is the fix not life yet?

**Comment by Tinyfin-github** [comment]
> @slowtorta this issue is still present? is the fix not life yet?

There was no update. Yesterday's restart was just the weekly honor restart.

**Comment by geojak** [comment]
@Tinyfin-github still not fixed even ater multiple restarts since then

**Comment by excelyte** [comment]
Nope, still not working
https://youtu.be/aqLJeYhnqyU

**Comment by SabineWren** [comment]
The quest works now, but only one time each. Dalaran has rep items, so maybe these quests should be daily?
