### ISSUE TITLE
Quest: Medium Magical Fortifications

### ISSUE THREAD

**Issue by Aeliren** [slowtorta/turtlewow-bug-tracker#2789]
The quest "Medium Magical Fortifications" from Magus Palon at Dalaran does not allow me to complete it even though I have the required items. I've previously relogged and cleared my WDB while attempting its lesser counterpart "Minor Magical Fortifications" to no effect.

![image](https://user-images.githubusercontent.com/96898927/215679534-45aef7ed-fa04-4852-8a8d-95120eb018ce.png)

**Steps to reproduce the behavior with as much detail as possible:**

1. Acquire the quest "Medium Magical Fortifications" from Magus Palon at Dalaran in the Alterac Mountains.
2. Have a Small Radiant Shard in your bag.
3. Attempt to turn in the quest.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=61065
Item: https://database.turtle-wow.org/?item=11177
Quest: https://database.turtle-wow.org/?quest=40710

**Expected behavior. Describe how it should work:**

I should be capable of turning in my quest when I have the Small Radiant Shard.

**Comment by cyaohiri** [comment]
Abandoning and retaking the quest should fix it.

**Comment by geojak** [comment]
@slowtorta still not fixed even ater multiple restarts since then
