### ISSUE TITLE
Truefaith Vestments requires tailoring after 2023 February 22 patch

### ISSUE THREAD

**Issue by kstiefer** [slowtorta/turtlewow-bug-tracker#2881]
**Please, provide a clear description what the bug is:**
The 2023 Feb 20 patch notes say: "Removed Tailoring skill requirement from the following items: Truefaith Vestments, Robe of the Void, Robe of the Archmage."
https://forum.turtle-wow.org/viewtopic.php?t=5658

At this time (Feb 22) I can see that the Truefaith Vestments shows the tailoring requirement in the turtle wow database and in game and I am unable to equip them without tailoring.

At this time, the turtle wow database also shows that Robe of the Void and Robe of the Archmage do not have a tailoring requirement.

**Steps to reproduce the behavior with as much detail as possible:**
1. Look at the Truefaith Vestments in the Turtle Wow Database to see the Tailoring Requirement
2. Make Truefaith Vestments
3. Remove tailoring
4. Try to equip Truefaith Vestments without tailoring

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**
Item: https://database.turtle-wow.org/?item=14154

**Expected behavior. Describe how it should work:**
Based on the 2023 Feb 20 patch notes, I expect to be able to equip Truefaith Vestments without tailoring.

**Comment by Zebouski** [comment]
Clear WDB and try again. your client can cache old versions of items, and clearing the cache will request a new copy of the item and its stats/requirements from the server, that you client can then know how to obey

**Comment by slowtorta** [comment]
It was indeed wrong. Please clear WDB and try again, should be fixed now.

**Comment by kstiefer** [comment]
At this time, I am able to equip Truefaith Vestments without tailoring, but I still see the tailoring requirement on the website:
https://database.turtle-wow.org/?item=14154

**Comment by slowtorta** [comment]
You need to delete WDB folder.
