### ISSUE TITLE
The new consumables use duplicated spell visual+spell icon that cause problems with aura stacking

### ISSUE THREAD

**Issue by balakethelock** [slowtorta/turtlewow-bug-tracker#4592]
**Please, provide a clear description what the bug is:**
The applied buff of the new elixirs, Dreamtonic and Dreamshard Elixir, uses the same spell icon as existing elixirs which causes problems with stacking them.

**Steps to reproduce the behavior with as much detail as possible:**

1. Drink one of the new elixirs/potions
2. Look at the buff icon of that elixir/potion
3. Try to drink another elixir/potion that shares the same spell icon
4. Find that the two effects won't stack with each other
5. In addition to that, it makes the two buffs indistinguishable to addons for the purpose of tracking buffs on yourself and allies.

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

Spell:
https://database.turtle-wow.org/?spell=45489 Dreamtonic which shares spell icon with Arcane Elixir
https://database.turtle-wow.org/?spell=45427 Dreamshard Elixir which shares spell icon with Greater Arcane Elixir

https://database.turtle-wow.org/?spell=45988 Elixir of Greater Nature Power (not yet implemented on live server, so it's untested but it's very likely to suffer the same issue so best be proactive). Shares spell icon with nature protection potion and greater nature protection potion

**Expected behavior. Describe how it should work:**
If you want two elixirs or potions to stack with each other, they must not have the same spell icon. If you want them to not stack with each other, they should still have different spell icons for clarity purposes.

This bug requires a client-side fix.

**Comment by balakethelock** [comment]
There are some good icons that exist in the game files but are not used for any consumables/spells
https://www.wowhead.com/classic/icon=135264/inv-summerfest-firepotion
https://www.wowhead.com/classic/icon=134817/inv-potion-37
https://www.wowhead.com/classic/icon=134839/inv-potion-59

**Comment by VrogragFishslayer** [comment]
I would like to add that I have now tested https://database.turtle-wow.org/?spell=45988 

When I have Greater Nature POWER elixir on, then put on Greater Nature Protection potion OR Nature Protection Potion, the nature power buff is removed, and vice versa. So I can at least confirm that Balake is correction about the Nature Power Elixir having the same problem. (Turned out to be an expensive Naxx run)

**Comment by twowTurtReynolds** [comment]
![image](https://github.com/slowtorta/turtlewow-bug-tracker/assets/151180101/1af690e3-e47f-44ba-b920-92dec9000ee5)
This looks to have been fixed?

**Comment by balakethelock** [comment]
> ![image](https://private-user-images.githubusercontent.com/151180101/288080404-1af690e3-e47f-44ba-b920-92dec9000ee5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MDE3NDMsIm5iZiI6MTcwMTgwMTQ0MywicGF0aCI6Ii8xNTExODAxMDEvMjg4MDgwNDA0LTFhZjY5MGUzLWU0N2YtNDRiYS1iOTIwLTkyZGVjOTAwMGVlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNVQxODM3MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTg5ZDY5NTA2YjUwMzE3NzE5MzMzMmZmYjI4NWU4M2ZkNGE5ZGU0NzVmZGU0ZmQ5ZTdmNjEyMjVhOTZkZTE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dIS2J2SiYBNuakH7WtmX1LenD41HytSv5wDQtlB89so) This looks to have been fixed?

Imo not fixed till they change the icons used. They still break addons and macros used to track consumables.

even besides that, it's simply unappealing and seems low quality when too many buffs share icons with each other, especially if those buffs are usually used by players in association with each other.

**Comment by twowTurtReynolds** [comment]
Oh, on second reading, I understand what you mean. Could you provide a few examples of addons that act up because of this?
