### ISSUE TITLE
tonal stone: kamino not working anymore

### ISSUE THREAD

**Issue by geojak** [slowtorta/turtlewow-bug-tracker#831]
**Please, provide a clear description what the bug is:**

helo my trinket unfortunely stopped working. nothing helped (wdp delete, relog, unequip and reequip) it will always say (you cannot use this right now). One other player atleast had the same problem 

**Steps to reproduce the behavior with as much detail as possible:**

1. get tona lstone kamino
2. Equip it and wait 30 seconds 
3. Try right clicking it
4. Doesn't work

**IDs of affected creatures, items, quests or spells with a link to the relevant page:**

NPC: https://database.turtle-wow.org/?npc=
Item: https://database.turtle-wow.org/?item=
Quest: https://database.turtle-wow.org/?quest=
Spell: https://database.turtle-wow.org/?spell=
Object: https://database.turtle-wow.org/?object=

**Expected behavior. Describe how it should work:**

trinket should work again playing musinc and aggroing stuf.

**Comment by slowtorta** [comment]
The trinket should not be aggroing anything, it was a bug. Music part is fixed tho :)

**Comment by geojak** [comment]
hey torta, thx for checking my issue. unfortuently it is still not fixed. i did delete WDB. not i displays the an on use to come protect my city and still says can not be used with no music. i assume you know this issue already thought trough discord. unfortuently i cant reopen the issue

**Comment by Tinyfin-github** [comment]
The fix has not been applied yet.  It will be applied at the next maintenance

**Comment by geojak** [comment]
ah ok, looking forward to the fix. thank you alot for the support. i love the custom quests!

**Comment by geojak** [comment]
its is working now again as of today. tooltip still wrong but i assume thats is in the pipe
