### ISSUE TITLE
Lunar Festival bugs so far

### ISSUE THREAD

**Issue by Ghirahim39** [slowtorta/turtlewow-bug-tracker#986]
I've noticed 5 issues with the lunar event so far, 2 of which seem to have already been reported.

1) Quest picked up in capital cities should only be for the capital city it was picked up in. Quest givers are currently offering three quests for all cities. [1]

2) The next quest, to launch fireworks, seems bugged as the objectives aren't completing. [2]
THIS HAS ALREADY BEEN REPORTED

3) Elders are giving rep for the opposite faction, and not giving rep for the new allied faction.
THIS HAS ALREADY BEEN REPORTED
3a) (Shouldn't even be able to see opposite faction iirc)

4) Elders aren't sending the letter by mail one hour after meeting them. [3]

5) The rewards for collecting coins can be purchased for a few copper. [4]

[1]: https://database.turtle-wow.org/?search=The+Lunar+Festival
[2]: https://database.turtle-wow.org/?quest=8867
[3]: https://database.turtle-wow.org/?item=21746
[4]: https://database.turtle-wow.org/?npc=15864

**Comment by Ghirahim39** [comment]
An additional reputation problem - rather than give 50 rep to each of the factions' cities it gives 50 rep split among them, so currently only 12 each.

**Comment by jameyboor** [comment]
Fixed #2 & #5.

**Comment by dshwedovsky-sc** [comment]
Server restarted. WDB removed. 
But throwing fireworks to cluster still not count for quest objective of Lunar Fireworks.

**Comment by Gasan918** [comment]
No firework animation

Turtle WOW
![image](https://user-images.githubusercontent.com/96973359/152698110-cd51e6c1-8ad1-446a-bf69-04b8be01b5aa.png)

Some Vanilla server:
![image](https://user-images.githubusercontent.com/96973359/152698141-a65557c6-68f1-4f68-af08-dc1e7f0c90e7.png)

**Comment by jameyboor** [comment]
Yes, this will be fixed in the next server update. Past server update did not include this fix but this is fixed on PTR.
